Repository Whist-Team/Whist-Browser, pull requests merged in 2022-06, with the labels that each got.

#9 SETUP: basic tech stack and run
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  index.html
  src/main.rs
Labels: enhancement

#10 ADD: github pages deployment
  .github/deploy.yml
Labels: ci/cd

#11 ADD: dependabot
  .github/dependabot.yml
Labels: ci/cd

#8 ADD: ci
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .runConfigurations/Run whist_browser.run.xml
  Cargo.lock
  Cargo.toml
  README.md
  index.html
  src/lib.rs
  src/main.rs
Labels: ci/cd

#16 FIX: missing dependencies
  README.md
Labels: documentation

#20 FEATURE: format checker run config
  .runConfigurations/Format Check.run.xml
Labels: enhancement

#17 FEATURE: server connection
  .github/workflows/main.yml
  .runConfigurations/Test.run.xml
  Cargo.lock
  Cargo.toml
  README.md
  src/lib.rs
  src/response/whist_info.rs
  src/server_connection.rs
Labels: enhancement

#21 Fix CI/CD
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: ci/cd

#24 ADD: coverage badge
  README.md
Labels: documentation, ci/cd

#31 Fix a few inconsistencies and refactor HTTP client wrapper
  src/network/server_connection.rs
  src/network/server_service.rs
  src/network/whist_info.rs
Labels: enhancement

#33 Add card data structures
  Cargo.lock
  Cargo.toml
  src/card.rs
  src/lib.rs
Labels: enhancement

#35 Implement user routes and streamline error handling
  Cargo.lock
  src/card.rs
  src/network/mod.rs
  src/network/server_connection.rs
  src/network/server_service.rs
  src/network/user.rs
  src/network/whist_info.rs
Labels: enhancement

#36 Login
  .cargo/config.toml
  .runConfigurations/Run wasm.run.xml
  Cargo.lock
  Cargo.toml
  src/connect.rs
  src/lib.rs
  src/login.rs
  src/main.rs
  src/network/async_worker.rs
  src/network/mod.rs
  src/network/plugin.rs
  src/network/server_connection.rs
  src/network/server_service.rs
  src/network/user.rs
  src/network/whist_info.rs
Labels: enhancement

#38 Add game list/join/create routes and very basic ui
  Cargo.lock
  src/connect.rs
  src/lib.rs
  src/login.rs
  src/network/game.rs
  src/network/mod.rs
  src/network/plugin.rs
  src/network/server_connection.rs
  src/network/server_service.rs
  src/network/user.rs
  src/network/whist_info.rs
  src/rooms.rs
Labels: enhancement

#44 Use semver to check server and core version compatibility
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/network/server_service.rs
  src/network/whist_info.rs
Labels: enhancement
